### ISSUE TITLE
在解析错误堆栈的时候，不能解析报错

### ISSUE THREAD

**Issue by jsjett** [aliyunmq/mq-http-nodejs-sdk#7]
`var parseString = require('xml2js').parseString;

function format(params) {
    if (typeof params === 'string') {
        return params;
    }

    var xml = '';
    Object.keys(params).forEach((key) => {
        const value = params[key];
        if (typeof value === 'object') {
            xml += `<${key}>${format(value)}</${key}>`;
        } else {
            xml += `<${key}>${value}</${key}>`;
        }
    });
    return xml;
}
function toXMLBuffer(entityType, params, subType) {
    var xml = '<?xml version="1.0" encoding="UTF-8"?>';
    xml += `<${entityType} xmlns="http://mq.aliyuncs.com/doc/v1/">`;
    if (Array.isArray(params)) {
        params.forEach((item) => {
            xml += `<${subType}>`;
            xml += format(item);
            xml += `</${subType}>`;
        });
    } else {
        xml += format(params);
    }
    xml += `</${entityType}>`;
    return Buffer.from(xml, 'utf8');
};

const msgBody = { "traceId": "cce4078fa92b4bb7b6bae9d9d256a154", "renderParams": [{ "params": "[{\"descWidth\":\"790\",\"maxHeight\":\"1546\",\"platForm\":\"4:790:1546\"}]", "key": "intelligentArt/user/524/personTemplate/18fb086e-5f8b-455c-be91-2c35fb2d6e75.json", "renderOs": "windows" }], "clientType": "pc", "stage": "SECOND", "sliceRecordId": 6903, "renderRedirectTag": "IDPT-DESCSLICERUNNER", "type": "4", "env": "alpha3", "taskId": "f18a3aea-9f2f-4a8a-a0a2-f79c92cb778c", "redirectTag": "IDPT-SLICERECORDJOBRUNNER" }

// 正常的
// msgBody.errorMsg = 'adcadasdasdas'
// 报错的
msgBody.errorMsg = "TypeError: Cannot read property 'includes' of undefined\n    at http://testeditor3.kuaimai.com/static/js/screenshot.65fc3f.js:1:1131367\n    at Array.forEach (<anonymous>)\n    at http://testeditor3.kuaimai.com/static/js/screenshot.65fc3f.js:1:1131344\n    at Array.forEach (<anonymous>)\n    at changeWindowJson (http://testeditor3.kuaimai.com/static/js/screenshot.65fc3f.js:1:1131029)\n    at http://testeditor3.kuaimai.com/static/js/screenshot.65fc3f.js:1:1130379\n    at l (http://testeditor3.kuaimai.com/static/js/vendor.490d17.js:1:362792)\n    at Generator._invoke (http://testeditor3.kuaimai.com/static/js/vendor.490d17.js:1:362545)\n    at Generator.next (http://testeditor3.kuaimai.com/static/js/vendor.490d17.js:1:363151)\n    at n (http://testeditor3.kuaimai.com/static/js/vendor.490d17.js:1:331871)"

const params = {
    MessageBody: JSON.stringify(msgBody)
}

const buff = toXMLBuffer('Message', params)

var xml = buff.toString()

parseString(xml, function (err, result) {
    console.log(err)
    console.log('----')
    console.dir(result);
});
`

上面的方法是mq源码里找到的 在解析的时候报错了 可以直接贴代码运行

**Comment by jsjett** [comment]
文档格式化有点问题 直接贴代码就能复现
